### PR TITLE
Add nodejs as a new runtime name

### PR DESCRIPTION
**Pull request by imikay**
On Debian, node js executable is called nodejs, so I suggest adding nodejs as a new runtime name.

### CODE REVIEW

**Comment by nacmartin** [comment]
Uhm, in this case instead of defining a new runner it may be better to be able to pass an array of possible names to `ExternalRuntime` and let it pick the first available (in order of appearance).

Similar as what the Rails people do here: https://github.com/rails/execjs/blob/99bdbb80673b0d800368370ebd215f93dfb50f49/lib/execjs/runtimes.rb#L20

**Comment by imikay** [comment]
Yes, this is better than defining a new runner, I will make some changes and recommit later.

**Comment by nacmartin** [comment]
Thanks for taking the time. I think that this is very important to have. :+1:

**Comment by imikay** [comment]
Hi, can you look into the coding style problem for me, StyleCI drives me crazy, I don't know what's the problem, seems that it's lack empty space after comment block? Thanks.

**Comment by imikay** [comment]
Also check the code please, I have finished.

**Comment by nacmartin** [comment]
Yeah, I will check it, don't worry about the StyleCI at all. Thanks!

**Comment by imikay** [comment]
Thanks. :+1:

**Pull request merged**
